datagrid:
    luaUpdater:
        options:
            entityHint: luaUpdater
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: ClickAndMortar\AdvancedCsvConnectorBundle\Entity\LuaUpdater
            repository_method: createDatagridQueryBuilder
        columns:
            label:
                label: pim_custom_entity.form.field.label.label
            code:
                label: pim_custom_entity.form.field.label.code
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_rest_get
                params:
                - id
                - customEntityName
            delete_link:
                type: url
                route: pim_customentity_rest_delete
                params:
                - id
                - customEntityName
        actions:
            edit:
                type:      navigate
                acl_resource: candm_advanced_csv_connector_luaUpdater_edit
                label:     luaUpdater.this.edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                acl_resource: candm_advanced_csv_connector_luaUpdater_delete
                label: luaUpdater.this.delete
                icon:  trash
                link:  delete_link
        filters:
            columns:
                label:
                    type:      string
                    label:     pim_custom_entity.form.field.label.label
                    data_name: rd.label
                code:
                    type:      string
                    label:     pim_custom_entity.form.field.label.code
                    data_name: rd.code
        sorters:
            columns:
                label:
                    data_name: rd.label
                code:
                    data_name: rd.code
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        mass_actions:
            delete:
                type: delete
                label: pim.grid.mass_action.delete
                entity_name: brand
                acl_resource: ~
                handler: mass_delete
                className: 'AknButton AknButton--important AknButtonList-item'
                messages:
                    confirm_title: pim_datagrid.mass_action.delete.confirm_title
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: OK
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection