# Reference data
## Import Mapping
candm_advanced_csv_connector_importMapping_index:
    type: action
    label: candm_advanced_csv_connector.acl.importMapping.index
    group_name: pim_custom_entity.acl_group.reference_data

candm_advanced_csv_connector_importMapping_create:
    type: action
    label: candm_advanced_csv_connector.acl.importMapping.create
    group_name: pim_custom_entity.acl_group.reference_data

candm_advanced_csv_connector_importMapping_edit:
    type: action
    label: candm_advanced_csv_connector.acl.importMapping.edit
    group_name: pim_custom_entity.acl_group.reference_data

candm_advanced_csv_connector_importMapping_delete:
    type: action
    label: candm_advanced_csv_connector.acl.importMapping.delete
    group_name: pim_custom_entity.acl_group.reference_data