# Reference data
## Mapping
candm_advanced_csv_connector_mapping_index:
    type: action
    label: candm_advanced_csv_connector.acl.mapping.index
    group_name: pim_custom_entity.acl_group.reference_data

candm_advanced_csv_connector_mapping_create:
    type: action
    label: candm_advanced_csv_connector.acl.mapping.create
    group_name: pim_custom_entity.acl_group.reference_data

candm_advanced_csv_connector_mapping_edit:
    type: action
    label: candm_advanced_csv_connector.acl.mapping.edit
    group_name: pim_custom_entity.acl_group.reference_data

candm_advanced_csv_connector_mapping_delete:
    type: action
    label: candm_advanced_csv_connector.acl.mapping.delete
    group_name: pim_custom_entity.acl_group.reference_data