parameters:
    candm_advanced_csv_connector.helper.import.class: ClickAndMortar\AdvancedCsvConnectorBundle\Helper\ImportHelper
    candm_advanced_csv_connector.helper.export.class: ClickAndMortar\AdvancedCsvConnectorBundle\Helper\ExportHelper

services:
    candm_advanced_csv_connector.helper.import:
        class: '%candm_advanced_csv_connector.helper.import.class%'
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'
            - '%kernel.root_dir%'
            - '%data_in_directory%'

    candm_advanced_csv_connector.helper.export:
        class: %candm_advanced_csv_connector.helper.export.class%
        arguments:
            - '@doctrine.orm.entity_manager'