parameters:
    candm_advanced_csv_connector.job.job_parameters.default_values_provider.product_csv_advanced_import.class: ClickAndMortar\AdvancedCsvConnectorBundle\Job\JobParameters\DefaultValuesProvider\ProductCsvAdvancedImport
    candm_advanced_csv_connector.job.job_parameters.default_values_provider.product_csv_advanced_export.class: ClickAndMortar\AdvancedCsvConnectorBundle\Job\JobParameters\DefaultValuesProvider\ProductCsvAdvancedExport

services:
    candm_advanced_csv_connector.job.job_parameters.default_values_provider.product_csv_advanced_import:
        class: '%candm_advanced_csv_connector.job.job_parameters.default_values_provider.product_csv_advanced_import.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.product_csv_import'
            -
                - '%candm_advanced_csv_connector.job_name.csv_advanced_product_import%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    candm_advanced_csv_connector.job.job_parameters.default_values_provider.product_csv_advanced_export:
        class: '%candm_advanced_csv_connector.job.job_parameters.default_values_provider.product_csv_advanced_export.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.product_csv_export'
            -
                - '%candm_advanced_csv_connector.job_name.csv_advanced_product_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
