parameters:
    candm_advanced_csv_connector.connector_name.csv: 'Click And Mortar Advanced CSV Connector'
    candm_advanced_csv_connector.job_name.csv_advanced_product_import: 'csv_advanced_product_import'
    candm_advanced_csv_connector.job_name.csv_advanced_product_model_import: 'csv_advanced_product_model_import'
    candm_advanced_csv_connector.job_name.csv_advanced_product_export: 'csv_advanced_product_export'
    candm_advanced_csv_connector.job_name.csv_advanced_product_model_export: 'csv_advanced_product_model_export'

services:
    candm_advanced_csv_connector.job.csv_advanced_product_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%candm_advanced_csv_connector.job_name.csv_advanced_product_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@akeneo.job_automation.connector.step.download'
                - '@candm_advanced_csv_connector.step.csv_advanced_product.import'
                - '@candm_advanced_csv_connector.step.mail_notification'
        tags:
            - { name: akeneo_batch.job, connector: '%candm_advanced_csv_connector.connector_name.csv%', type: '%pim_connector.job.import_type%' }

    candm_advanced_csv_connector.job.csv_advanced_product_model_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%candm_advanced_csv_connector.job_name.csv_advanced_product_model_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@akeneo.job_automation.connector.step.download'
                - '@candm_advanced_csv_connector.step.csv_advanced_root_product_model.import'
                - '@candm_advanced_csv_connector.step.csv_advanced_sub_product_model.import'
                - '@candm_advanced_csv_connector.step.mail_notification'
        tags:
            - { name: akeneo_batch.job, connector: '%candm_advanced_csv_connector.connector_name.csv%', type: '%pim_connector.job.import_type%' }

    candm_advanced_csv_connector.job.csv_advanced_product_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%candm_advanced_csv_connector.job_name.csv_advanced_product_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@candm_advanced_csv_connector.step.csv_advanced_product.export'
                - '@akeneo.job_automation.connector.step.upload'
        tags:
            - { name: akeneo_batch.job, connector: '%candm_advanced_csv_connector.connector_name.csv%', type: '%pim_connector.job.export_type%' }

    candm_advanced_csv_connector.job.csv_advanced_product_model_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%candm_advanced_csv_connector.job_name.csv_advanced_product_model_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@candm_advanced_csv_connector.step.csv_advanced_product_model.export'
                - '@akeneo.job_automation.connector.step.upload'
        tags:
        - { name: akeneo_batch.job, connector: '%candm_advanced_csv_connector.connector_name.csv%', type: '%pim_connector.job.export_type%' }
