# Normalizers
services:
    pim_custom_entity.normalizer.standard.importMapping:
        public: false
        class: ClickAndMortar\AdvancedCsvConnectorBundle\Normalizer\Standard\ImportMappingNormalizer
        tags:
        - { name: pim_serializer.normalizer, priority: 200 }