# Normalizers
services:
    pim_custom_entity.normalizer.standard.importMapping:
        public: false
        class: ClickAndMortar\AdvancedCsvConnectorBundle\Normalizer\Standard\ImportMappingNormalizer
        tags:
        - { name: pim_serializer.normalizer, priority: 200 }

    pim_custom_entity.normalizer.standard.exportMapping:
        public: false
        class: ClickAndMortar\AdvancedCsvConnectorBundle\Normalizer\Standard\ExportMappingNormalizer
        tags:
        - { name: pim_serializer.normalizer, priority: 200 }

    pim_custom_entity.normalizer.standard.luaUpdater:
        public: false
        class: ClickAndMortar\AdvancedCsvConnectorBundle\Normalizer\Standard\LuaUpdaterNormalizer
        tags:
        - { name: pim_serializer.normalizer, priority: 200 }