# Normalizers
services:
    pim_custom_entity.normalizer.standard.mapping:
        public: false
        class: ClickAndMortar\AdvancedCsvConnectorBundle\Normalizer\Standard\MappingNormalizer
        tags:
        - { name: pim_serializer.normalizer, priority: 200 }