parameters:
    candm_advanced_csv_connector.processor.normalization.advanced_product.class: ClickAndMortar\AdvancedCsvConnectorBundle\Processor\Normalization\AdvancedProductProcessor

services:
    candm_advanced_csv_connector.processor.normalization.advanced_product:
        class: '%candm_advanced_csv_connector.processor.normalization.advanced_product.class%'
        arguments:
            - '@pim_catalog.normalizer.standard.product'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.processor.bulk_media_fetcher'
            - '@pim_catalog.values_filler.product'
            - '%media_url_prefix%'