services:
    candm_advanced_csv_connector.provider.form.job_instance:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                csv_advanced_product_import: pim-job-instance-csv-advanced-product-import
                csv_advanced_product_export: pim-job-instance-csv-advanced-product-export
                csv_advanced_product_model_import: pim-job-instance-csv-advanced-product-model-import
        tags:
            - { name: pim_enrich.provider.form }
