parameters:
    candm_advanced_csv_connector.reader.file.csv_advanced_product.class: ClickAndMortar\AdvancedCsvConnectorBundle\Reader\File\Csv\ProductAdvancedReader
    candm_advanced_csv_connector.reader.file.csv_advanced_product_model.class: ClickAndMortar\AdvancedCsvConnectorBundle\Reader\File\Csv\ProductModelAdvancedReader

services:
    candm_advanced_csv_connector.reader.file.csv_advanced_product:
        class: '%candm_advanced_csv_connector.reader.file.csv_advanced_product.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.product_delocalized'
            - '@pim_connector.reader.file.media_path_transformer'
            - []
            - '@candm_advanced_csv_connector.helper.import'
            - '@pim_catalog.repository.product'
            - '@candm_advanced_csv_connector.repository.import_mapping'
            - '@candm_advanced_csv_connector.repository.lua_updater'

    candm_advanced_csv_connector.reader.file.csv_advanced_product_model:
        class: '%candm_advanced_csv_connector.reader.file.csv_advanced_product_model.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@pim_connector.array_converter.flat_to_standard.product_model_delocalized'
            - '@pim_connector.reader.file.media_path_transformer'
            - []
            - '@candm_advanced_csv_connector.helper.import'
            - '@pim_catalog.repository.product_model'
            - '@candm_advanced_csv_connector.repository.import_mapping'
            - '@candm_advanced_csv_connector.repository.lua_updater'