parameters:
    candm_advanced_csv_connector.repository.attribute_option.class: ClickAndMortar\AdvancedCsvConnectorBundle\Doctrine\ORM\Repository\AttributeOptionRepository
    candm_advanced_csv_connector.repository.import_mapping.class: ClickAndMortar\AdvancedCsvConnectorBundle\Doctrine\ORM\Repository\ImportMappingRepository

services:
    candm_advanced_csv_connector.repository.import_mapping:
        class: '%candm_advanced_csv_connector.repository.import_mapping.class%'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_custom_entity.entity.importMapping.class%']
        tags:
            - { name: 'pim_repository' }