config:
    paths:
        tabulator: clickandmortaradvancedcsvconnector/js/lib/tabulator

        # Mapping field
        pim/form/common/fields/import-mapping: clickandmortaradvancedcsvconnector/js/form/common/fields/import-mapping
        pim/template/form/common/fields/import-mapping: clickandmortaradvancedcsvconnector/templates/form/common/fields/import-mapping.html