parameters:
    pim_connector.step.product.import.bulk_size: 100
    candm_advanced_csv_connector.step.mail_notification.class: 'ClickAndMortar\AdvancedCsvConnectorBundle\Step\MailNotification'

services:
    candm_advanced_csv_connector.step.csv_advanced_product.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@candm_advanced_csv_connector.reader.file.csv_advanced_product'
            - '@pim_connector.processor.denormalization.product'
            - '@pim_connector.writer.database.product'
            - '%pim_connector.step.product.import.bulk_size%'

    candm_advanced_csv_connector.step.csv_advanced_root_product_model.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_root_product_model'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@candm_advanced_csv_connector.reader.file.csv_advanced_product_model'
            - '@pim_connector.processor.denormalization.root_product_model'
            - '@pim_connector.writer.database.product_model'
            - '%pim_job_product_batch_size%'

    candm_advanced_csv_connector.step.csv_advanced_sub_product_model.import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_sub_product_model'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@candm_advanced_csv_connector.reader.file.csv_advanced_product_model'
            - '@pim_connector.processor.denormalization.sub_product_model'
            - '@pim_connector.writer.database.product_model'
            - '%pim_job_product_batch_size%'

    candm_advanced_csv_connector.step.csv_advanced_product.export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@pim_connector.processor.normalization.product'
            - '@candm_advanced_csv_connector.writer.file.csv_advanced_product'
            - 10

    candm_advanced_csv_connector.step.csv_advanced_product_model.export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product_model'
            - '@pim_connector.processor.normalization.product_model'
            - '@candm_advanced_csv_connector.writer.file.csv_advanced_product_model'
            - '%pim_job_product_batch_size%'

    candm_advanced_csv_connector.step.mail_notification:
        class: '%candm_advanced_csv_connector.step.mail_notification.class%'
        arguments:
            - 'notification'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_notification.email.email_notifier'
            - '@templating'
            - '@translator'
