ClickAndMortar\AdvancedCsvConnectorBundle\Entity\ImportMapping:
    properties:
        label:
        - NotBlank: ~
        code:
        - NotBlank: ~

ClickAndMortar\AdvancedCsvConnectorBundle\Entity\ExportMapping:
    properties:
        label:
        - NotBlank: ~
        code:
        - NotBlank: ~

ClickAndMortar\AdvancedCsvConnectorBundle\Entity\LuaUpdater:
    constraints:
    -   ClickAndMortar\AdvancedCsvConnectorBundle\Validator\Constraints\LuaScriptConstraint: ~
    properties:
        label:
        - NotBlank: ~
        code:
        - NotBlank: ~