extensions:
    pim-mapping-edit-form:
        module: pim/form/common/edit-form

    pim-mapping-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-mapping-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: candm_advanced_csv_connector-menu-reference_data-item-mapping

    pim-mapping-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-mapping-edit-form
        position: 1000

    pim-color-edit-form-label:
        module: custom_entity/form/common/label
        parent: pim-color-edit-form
        targetZone: title
        position: 90

    pim-mapping-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-mapping-edit-form
        targetZone: content
        position: 100

    pim-mapping-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-mapping-edit-form
        targetZone: buttons
        position: 50

    pim-mapping-edit-form-delete:
        module: custom_entity/form/common/delete
        parent: pim-mapping-edit-form-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_enrich_group_remove
        position: 100
        config:
            route: pim_customentity_rest_delete
            routeParams:
                customEntityName: mapping
            trans:
                title: candm_advanced_csv_connector.mapping.message.delete
                container: pim_enrich.confirmation.delete_item
                success: pim_custom_entity.message.removed
                fail: pim_custom_entity.error.removing
            redirect: pim_customentity_index

    pim-mapping-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-mapping-edit-form
        targetZone: buttons
        position: 120

    pim-mapping-edit-form-state:
        module: pim/form/common/state
        parent: pim-mapping-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-mapping-edit-form-save:
        module: custom_entity/form/common/save-form
        parent: pim-mapping-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: pim_enrich.entity.attribute.info.update_successful
            updateFailureMessage: pim_enrich.entity.attribute.info.update_failed
            notReadyMessage: pim_enrich.entity.attribute.info.field_not_ready
            url: pim_customentity_rest_edit
            route_params:
                customEntityName: mapping
            redirectAfter: pim_customentity_rest_get
            excludedProperties: ['data']

    pim-mapping-edit-form-properties-tab:
        module: pim/common/tab
        parent: pim-mapping-edit-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: pim_custom_entity.form.tab.properties.title

    pim-mapping-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-mapping-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-mapping-edit-form-state:
        module: pim/form/common/state
        parent: pim-mapping-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-mapping-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-mapping-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-mapping-edit-form-properties-common:
        module: pim/common/simple-view
        parent: pim-mapping-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_custom_entity.form.tab.properties.section.common
                dropZone: content

    pim-mapping-edit-form-properties-label:
        module: pim/form/common/fields/text
        parent: pim-mapping-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: label
            label: candm_advanced_csv_connector.mapping.field.label.label
            required: true

    pim-mapping-edit-form-properties-code:
        module: pim/form/common/fields/text
        parent: pim-mapping-edit-form-properties-common
        targetZone: content
        position: 100
        config:
            fieldName: code
            label: candm_advanced_csv_connector.mapping.field.label.code
            required: true

    pim-mapping-edit-form-properties-mapping:
        module: pim/form/common/fields/mapping
        parent: pim-mapping-edit-form-properties-common
        targetZone: content
        position: 110
        config:
            fieldName: code
            label: candm_advanced_csv_connector.mapping.field.label.mapping