extensions:
    pim-mapping-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    pim-mapping-index-grid-container:
        module: pim/common/simple-view
        parent: pim-mapping-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pim-mapping-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-mapping-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-mapping-index-grid-title:
        module: pim/common/grid-title
        parent: pim-mapping-index
        targetZone: title
        config:
            title: candm_advanced_csv_connector.mapping.index_title

    pim-mapping-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-mapping-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: candm_advanced_csv_connector-menu-reference_data-item-mapping

    pim-mapping-index-grid-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-mapping-index-grid-container
        targetZone: filters

    pim-mapping-index-grid-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-mapping-index-grid-container
        targetZone: filters

    pim-mapping-index-mass-actions:
        module: pim/grid/mass-actions
        parent: pim-mapping-index
        targetZone: bottom-panel
        config:
            label: candm_advanced_csv_connector.mapping.selected

    pim-mapping-index-actions-panel:
        module: oro/datagrid/actions-panel
        parent: pim-mapping-index-mass-actions
        targetZone: actions-panel

    pim-mapping-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-mapping-index-grid-container
        targetZone: toolbar
        config:
            gridName: mapping

    pim-mapping-index-grid:
        module: pim/form/common/index/grid
        parent: pim-mapping-index
        targetZone: content
        position: 1000
        config:
            alias: mapping

    pim-mapping-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-mapping-index
        targetZone: buttons
        aclResourceId: pim_enrich_product_create
        config:
            title:     pim_custom_entity.button.create
            modalForm: pim-mapping-create-modal