extensions:
    candm_advanced_csv_connector-menu-reference_data-item-importMapping:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 10
        config:
            title: candm_advanced_csv_connector.menu.item.reference_data.importMapping
            to: pim_customentity_index
            routeParams:
                customEntityName: importMapping

    candm_advanced_csv_connector-menu-reference_data-item-exportMapping:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 20
        config:
            title: candm_advanced_csv_connector.menu.item.reference_data.exportMapping
            to: pim_customentity_index
            routeParams:
                customEntityName: exportMapping

    candm_advanced_csv_connector-menu-reference_data-item-luaUpdater:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 30
        config:
            title: candm_advanced_csv_connector.menu.item.reference_data.luaUpdater
            to: pim_customentity_index
            routeParams:
                customEntityName: luaUpdater