extensions:
    pim-exportMapping-create-modal:
        module: custom_entity/form/creation/modal
        config:
            labels:
                title: pim_custom_entity.create_popin.title
                subTitle: candm_advanced_csv_connector.menu.item.reference_data.exportMapping
            picture: illustrations/User.svg
            successMessage: pim_custom_entity.message.created
            editRoute: pim_customentity_rest_get
            postUrl:
                route: pim_customentity_rest_create
                parameters:
                    customEntityName: exportMapping

    pim-exportMapping-create-label:
        module: pim/form/common/creation/field
        parent: pim-exportMapping-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: label
            label: pim_custom_entity.form.field.label.label

    pim-exportMapping-create-code:
        module: pim/form/common/creation/field
        parent: pim-exportMapping-create-modal
        targetZone: fields
        position: 20
        config:
            identifier: code
            label: pim_custom_entity.form.field.label.code